### ISSUE TITLE
Test HBMNL model on simulated data

### ISSUE THREAD

**Issue by dgmiller** [marcdotson/conjoint-ensembles#1]

**Comment by dgmiller** [comment]
@marcdotson In response to [your model comparison](https://github.com/marcdotson/ra-training/blob/hmnl-comparison/Comparing_Choice_Models.md) I was bugged enough to run some tests on the centered vs non-centered parameterizations. I varied the adapt_delta parameter. Behold the images. I ran them on a very small data set of 2 respondents, 15 choice tasks, 2 alternatives, 3 feature-levels.

Histograms of the betas (the row corresponds to the respondent, the column to the feature)

**NON-CENTERED**
adapt_delta = .8, .9, .95
<img width="735" alt="nc8" src="https://user-images.githubusercontent.com/8867096/58898026-47069500-86bf-11e9-911e-fdd6e00e3799.png">
<img width="738" alt="nc9" src="https://user-images.githubusercontent.com/8867096/58897996-3c4c0000-86bf-11e9-9a57-d552c1ea89ba.png">
<img width="729" alt="nc95" src="https://user-images.githubusercontent.com/8867096/58898013-42da7780-86bf-11e9-94ae-5923f6f876c1.png">

**CENTERED**
adapt_delta = .8, .9, .95
<img width="739" alt="c8" src="https://user-images.githubusercontent.com/8867096/58898142-87661300-86bf-11e9-9f21-eb9d4c60764d.png">
<img width="745" alt="c9" src="https://user-images.githubusercontent.com/8867096/58898152-8df48a80-86bf-11e9-8279-f5117e5366af.png">
<img width="716" alt="c95" src="https://user-images.githubusercontent.com/8867096/58898163-92b93e80-86bf-11e9-97f5-51a817620479.png">

The histograms look roughly similar which is not too interesting. Now let's look at the "trace plots". The x-axis is the iteration or draw (out of 4000, 1000 from each of 4 chains) and the y-axis is the value for the beta drawn.

**NON-CENTERED**
adapt_delta = .8, .9, .95
<img width="748" alt="nc8p" src="https://user-images.githubusercontent.com/8867096/58898302-ecba0400-86bf-11e9-8bd4-452284111b6a.png">
<img width="753" alt="nc9p" src="https://user-images.githubusercontent.com/8867096/58898313-f04d8b00-86bf-11e9-8463-4ce96f326566.png">
<img width="742" alt="nc95p" src="https://user-images.githubusercontent.com/8867096/58898317-f2afe500-86bf-11e9-8565-4d994d8ac2c7.png">

**CENTERED**
adapt_delta = .8, .9, .95
<img width="754" alt="c8p" src="https://user-images.githubusercontent.com/8867096/58898328-fb082000-86bf-11e9-8213-0e06b3296f16.png">
<img width="737" alt="c9p" src="https://user-images.githubusercontent.com/8867096/58898338-fcd1e380-86bf-11e9-82ea-d116f2cc93ea.png">
<img width="724" alt="c95p" src="https://user-images.githubusercontent.com/8867096/58898340-fe9ba700-86bf-11e9-9860-d2a8e40dff55.png">


Now that's interesting. Both models seem to have systematic divergences (data on that below) but you can see the bias in the centered model whereas the uncentered model is still biased but less obviously so. Consider the table below.

```
model, adapt_delta, div rate, convergence (.9<Rhat<1.1)
n      .80          12.83%    Y
n      .90          05.30%    Y
n      .95          00.35%    Y
c      .80          00.75%    N
c      .90          01.03%    Y
c      .95          00.83%    N
```

I don't really have a conclusion for this yet except that we should maybe investigate this further, especially if we are using these in an ensemble. Could you try reproducing these results?

**Comment by marcdotson** [comment]
Thanks for reopening this, @dgmiller. I haven't gone back to simulations, but I thought I would share some interested results in comparing parameterizations from another study using real-live data!

The object of interest in this study are the estimates of the upper-level coefficient matrix. I've run it for centered, non-centered, and "conjugate" (a random-walk Metropolis Hastings MCMC using a conjugate inverse Wishart prior).

First the marginal posteriors for the upper-level:

**NON-CENTERED**
![intercept_marginal-posteriors_noncentered](https://user-images.githubusercontent.com/29615257/60056073-e30f3500-969c-11e9-8c6b-3fa7538bf604.png)

**CENTERED**
![intercept_marginal-posteriors_centered](https://user-images.githubusercontent.com/29615257/60056090-f6ba9b80-969c-11e9-8285-ecdd5baae2a0.png)

**CONJUGATE**
![intercept_marginal-posteriors_conjugate](https://user-images.githubusercontent.com/29615257/60056105-033ef400-969d-11e9-893f-b438de215cff.png)

As in simulation, they're all the same, so nothing really interesting there.

Now the traceplots (note that the conjugate model just had one chain; no fancy parallelization in the legacy code borne from my PhD).

**NON-CENTERED**
![intercept_trace_noncentered](https://user-images.githubusercontent.com/29615257/60056163-34b7bf80-969d-11e9-9b75-624241d8ed6b.png)

**CENTERED**
![intercept_trace_centered](https://user-images.githubusercontent.com/29615257/60056171-3d0ffa80-969d-11e9-925d-e5686202f5e7.png)

**CONJUGATE**
![intercept_trace_conjugate](https://user-images.githubusercontent.com/29615257/60056181-45683580-969d-11e9-8684-3fcbe259afc1.png)

Also, not very different, though the centered parameterization has traceplots that are wider, which corroborates with what you saw in simulation. That model also complained about tree depth and maybe one other HMC-specific diagnostic.

TBH, this is the very reason that the non-centered parameterization is encouraged, isn't it? In a hierarchical setting there are strange geometries in the posterior that need to be dealt with. I know I made a stink about my initial comparison, but I think there is probably something strange in terms of the simulated data or in the fact that there was just one simulated dataset. I'll get back to testing it since I think that will be a helpful something we could share on the blog-that-is-soon-to-be. But I thought these real-world comparisons were an interesting point to consider.

As a bonus, here's how long each parameterization took:

```
# Centered (2000 iterations): 17990.1 seconds (Total)
# Noncentered (2000 iterations): 5634.98 seconds (Total)
# Conjugate (100000 iterations): Total Time Elapsed (in Hours):  14.89
```
